// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/cmis.proto

package cmis

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Repository struct {
	Id                   *CmisID     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RootFolder           *CmisObject `protobuf:"bytes,3,opt,name=root_folder,json=rootFolder,proto3" json:"root_folder,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *Repository) Reset()         { *m = Repository{} }
func (m *Repository) String() string { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()    {}
func (*Repository) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{0}
}

func (m *Repository) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Repository.Unmarshal(m, b)
}
func (m *Repository) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Repository.Marshal(b, m, deterministic)
}
func (m *Repository) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Repository.Merge(m, src)
}
func (m *Repository) XXX_Size() int {
	return xxx_messageInfo_Repository.Size(m)
}
func (m *Repository) XXX_DiscardUnknown() {
	xxx_messageInfo_Repository.DiscardUnknown(m)
}

var xxx_messageInfo_Repository proto.InternalMessageInfo

func (m *Repository) GetId() *CmisID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Repository) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Repository) GetRootFolder() *CmisObject {
	if m != nil {
		return m.RootFolder
	}
	return nil
}

type TypeDefinition struct {
	Id                   *CmisID               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string                `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PropertyDefinitions  []*PropertyDefinition `protobuf:"bytes,3,rep,name=property_definitions,json=propertyDefinitions,proto3" json:"property_definitions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *TypeDefinition) Reset()         { *m = TypeDefinition{} }
func (m *TypeDefinition) String() string { return proto.CompactTextString(m) }
func (*TypeDefinition) ProtoMessage()    {}
func (*TypeDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{1}
}

func (m *TypeDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TypeDefinition.Unmarshal(m, b)
}
func (m *TypeDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TypeDefinition.Marshal(b, m, deterministic)
}
func (m *TypeDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TypeDefinition.Merge(m, src)
}
func (m *TypeDefinition) XXX_Size() int {
	return xxx_messageInfo_TypeDefinition.Size(m)
}
func (m *TypeDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_TypeDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_TypeDefinition proto.InternalMessageInfo

func (m *TypeDefinition) GetId() *CmisID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *TypeDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TypeDefinition) GetPropertyDefinitions() []*PropertyDefinition {
	if m != nil {
		return m.PropertyDefinitions
	}
	return nil
}

type PropertyDefinition struct {
	Id                   *CmisID  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PropertyDefinition) Reset()         { *m = PropertyDefinition{} }
func (m *PropertyDefinition) String() string { return proto.CompactTextString(m) }
func (*PropertyDefinition) ProtoMessage()    {}
func (*PropertyDefinition) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{2}
}

func (m *PropertyDefinition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PropertyDefinition.Unmarshal(m, b)
}
func (m *PropertyDefinition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PropertyDefinition.Marshal(b, m, deterministic)
}
func (m *PropertyDefinition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PropertyDefinition.Merge(m, src)
}
func (m *PropertyDefinition) XXX_Size() int {
	return xxx_messageInfo_PropertyDefinition.Size(m)
}
func (m *PropertyDefinition) XXX_DiscardUnknown() {
	xxx_messageInfo_PropertyDefinition.DiscardUnknown(m)
}

var xxx_messageInfo_PropertyDefinition proto.InternalMessageInfo

func (m *PropertyDefinition) GetId() *CmisID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *PropertyDefinition) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PropertyDefinition) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type CmisObject struct {
	Id                   *CmisID         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TypeDefinition       *TypeDefinition `protobuf:"bytes,2,opt,name=type_definition,json=typeDefinition,proto3" json:"type_definition,omitempty"`
	Properties           []*CmisProperty `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CmisObject) Reset()         { *m = CmisObject{} }
func (m *CmisObject) String() string { return proto.CompactTextString(m) }
func (*CmisObject) ProtoMessage()    {}
func (*CmisObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{3}
}

func (m *CmisObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmisObject.Unmarshal(m, b)
}
func (m *CmisObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmisObject.Marshal(b, m, deterministic)
}
func (m *CmisObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmisObject.Merge(m, src)
}
func (m *CmisObject) XXX_Size() int {
	return xxx_messageInfo_CmisObject.Size(m)
}
func (m *CmisObject) XXX_DiscardUnknown() {
	xxx_messageInfo_CmisObject.DiscardUnknown(m)
}

var xxx_messageInfo_CmisObject proto.InternalMessageInfo

func (m *CmisObject) GetId() *CmisID {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *CmisObject) GetTypeDefinition() *TypeDefinition {
	if m != nil {
		return m.TypeDefinition
	}
	return nil
}

func (m *CmisObject) GetProperties() []*CmisProperty {
	if m != nil {
		return m.Properties
	}
	return nil
}

type CmisProperty struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	PropertyDefinition   *PropertyDefinition `protobuf:"bytes,3,opt,name=property_definition,json=propertyDefinition,proto3" json:"property_definition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *CmisProperty) Reset()         { *m = CmisProperty{} }
func (m *CmisProperty) String() string { return proto.CompactTextString(m) }
func (*CmisProperty) ProtoMessage()    {}
func (*CmisProperty) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{4}
}

func (m *CmisProperty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmisProperty.Unmarshal(m, b)
}
func (m *CmisProperty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmisProperty.Marshal(b, m, deterministic)
}
func (m *CmisProperty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmisProperty.Merge(m, src)
}
func (m *CmisProperty) XXX_Size() int {
	return xxx_messageInfo_CmisProperty.Size(m)
}
func (m *CmisProperty) XXX_DiscardUnknown() {
	xxx_messageInfo_CmisProperty.DiscardUnknown(m)
}

var xxx_messageInfo_CmisProperty proto.InternalMessageInfo

func (m *CmisProperty) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CmisProperty) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *CmisProperty) GetPropertyDefinition() *PropertyDefinition {
	if m != nil {
		return m.PropertyDefinition
	}
	return nil
}

type CmisChildren struct {
	Children             []*CmisObject `protobuf:"bytes,1,rep,name=children,proto3" json:"children,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CmisChildren) Reset()         { *m = CmisChildren{} }
func (m *CmisChildren) String() string { return proto.CompactTextString(m) }
func (*CmisChildren) ProtoMessage()    {}
func (*CmisChildren) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{5}
}

func (m *CmisChildren) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmisChildren.Unmarshal(m, b)
}
func (m *CmisChildren) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmisChildren.Marshal(b, m, deterministic)
}
func (m *CmisChildren) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmisChildren.Merge(m, src)
}
func (m *CmisChildren) XXX_Size() int {
	return xxx_messageInfo_CmisChildren.Size(m)
}
func (m *CmisChildren) XXX_DiscardUnknown() {
	xxx_messageInfo_CmisChildren.DiscardUnknown(m)
}

var xxx_messageInfo_CmisChildren proto.InternalMessageInfo

func (m *CmisChildren) GetChildren() []*CmisObject {
	if m != nil {
		return m.Children
	}
	return nil
}

type CmisID struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmisID) Reset()         { *m = CmisID{} }
func (m *CmisID) String() string { return proto.CompactTextString(m) }
func (*CmisID) ProtoMessage()    {}
func (*CmisID) Descriptor() ([]byte, []int) {
	return fileDescriptor_5ed4f7310ba83cea, []int{6}
}

func (m *CmisID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmisID.Unmarshal(m, b)
}
func (m *CmisID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmisID.Marshal(b, m, deterministic)
}
func (m *CmisID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmisID.Merge(m, src)
}
func (m *CmisID) XXX_Size() int {
	return xxx_messageInfo_CmisID.Size(m)
}
func (m *CmisID) XXX_DiscardUnknown() {
	xxx_messageInfo_CmisID.DiscardUnknown(m)
}

var xxx_messageInfo_CmisID proto.InternalMessageInfo

func (m *CmisID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*Repository)(nil), "cmis.Repository")
	proto.RegisterType((*TypeDefinition)(nil), "cmis.TypeDefinition")
	proto.RegisterType((*PropertyDefinition)(nil), "cmis.PropertyDefinition")
	proto.RegisterType((*CmisObject)(nil), "cmis.CmisObject")
	proto.RegisterType((*CmisProperty)(nil), "cmis.CmisProperty")
	proto.RegisterType((*CmisChildren)(nil), "cmis.CmisChildren")
	proto.RegisterType((*CmisID)(nil), "cmis.CmisID")
}

func init() { proto.RegisterFile("proto/cmis.proto", fileDescriptor_5ed4f7310ba83cea) }

var fileDescriptor_5ed4f7310ba83cea = []byte{
	// 447 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xcf, 0x8b, 0xd3, 0x40,
	0x14, 0x66, 0xd2, 0x5a, 0xcc, 0x4b, 0xad, 0xcb, 0x6c, 0x91, 0x10, 0x3d, 0x94, 0x9c, 0x0a, 0x4a,
	0x8a, 0xd9, 0x93, 0xa0, 0x17, 0x77, 0x15, 0x16, 0x0f, 0xca, 0xe8, 0x69, 0x2f, 0x4b, 0x9b, 0xbc,
	0xc6, 0x91, 0x24, 0x33, 0x4e, 0x66, 0x17, 0x72, 0xf6, 0x0f, 0x10, 0xbc, 0xfb, 0xbf, 0x4a, 0x26,
	0x3f, 0x4b, 0x2a, 0x62, 0x6f, 0x2f, 0x33, 0xdf, 0xfb, 0xde, 0xfb, 0xbe, 0x37, 0x2f, 0x70, 0x26,
	0x95, 0xd0, 0x62, 0x13, 0x65, 0xbc, 0x08, 0x4c, 0x48, 0xa7, 0x55, 0xec, 0x3d, 0x4d, 0x84, 0x48,
	0x52, 0xdc, 0x98, 0xb3, 0xdd, 0xdd, 0x7e, 0x83, 0x99, 0xd4, 0x65, 0x0d, 0xf1, 0xbf, 0x03, 0x30,
	0x94, 0xa2, 0xe0, 0x5a, 0xa8, 0x92, 0x3e, 0x03, 0x8b, 0xc7, 0x2e, 0x59, 0x91, 0xb5, 0x13, 0xce,
	0x03, 0xc3, 0x74, 0x99, 0xf1, 0xe2, 0xfa, 0x8a, 0x59, 0x3c, 0xa6, 0x14, 0xa6, 0xf9, 0x36, 0x43,
	0xd7, 0x5a, 0x91, 0xb5, 0xcd, 0x4c, 0x4c, 0x5f, 0x82, 0xa3, 0x84, 0xd0, 0xb7, 0x7b, 0x91, 0xc6,
	0xa8, 0xdc, 0x89, 0x49, 0x3d, 0xeb, 0x53, 0x3f, 0xee, 0xbe, 0x61, 0xa4, 0x19, 0x54, 0xa0, 0xf7,
	0x06, 0xe3, 0xff, 0x24, 0xb0, 0xf8, 0x52, 0x4a, 0xbc, 0xc2, 0x3d, 0xcf, 0xb9, 0xe6, 0x22, 0x3f,
	0xa1, 0xee, 0x07, 0x58, 0x4a, 0x25, 0x24, 0x2a, 0x5d, 0xde, 0xc6, 0x1d, 0x51, 0xe1, 0x4e, 0x56,
	0x93, 0xb5, 0x13, 0xba, 0x35, 0xc7, 0xa7, 0x06, 0xd1, 0x57, 0x62, 0xe7, 0x72, 0x74, 0x56, 0xf8,
	0x37, 0x40, 0xc7, 0xd0, 0x13, 0x9a, 0xa2, 0x30, 0xd5, 0xa5, 0x44, 0xe3, 0x82, 0xcd, 0x4c, 0xec,
	0xff, 0x26, 0x00, 0xbd, 0x11, 0xff, 0x20, 0x7d, 0x03, 0x8f, 0xab, 0xa4, 0x81, 0x22, 0xc3, 0xef,
	0x84, 0xcb, 0x1a, 0x7a, 0x68, 0x1b, 0x5b, 0xe8, 0x43, 0x1b, 0x43, 0x80, 0x46, 0x1e, 0xc7, 0xd6,
	0x0a, 0xda, 0x17, 0x69, 0x35, 0xb2, 0x01, 0xca, 0xff, 0x41, 0x60, 0x3e, 0xbc, 0xec, 0x84, 0x91,
	0x81, 0xb0, 0x25, 0x3c, 0xb8, 0xdf, 0xa6, 0x77, 0xad, 0xda, 0xfa, 0x83, 0x5e, 0xc3, 0xf9, 0x91,
	0x19, 0x34, 0x6f, 0xe0, 0xef, 0x23, 0xa0, 0xe3, 0x11, 0xf8, 0xaf, 0xeb, 0x26, 0x2e, 0xbf, 0xf2,
	0x34, 0x56, 0x98, 0xd3, 0x17, 0xf0, 0x30, 0x6a, 0x62, 0x97, 0x18, 0x1d, 0xe3, 0x37, 0xd5, 0x21,
	0x7c, 0x17, 0x66, 0xb5, 0x89, 0x74, 0xd1, 0xd9, 0x6b, 0x57, 0x86, 0x86, 0xbf, 0x2c, 0x70, 0xaa,
	0xab, 0xcf, 0xa8, 0xee, 0x79, 0x84, 0xf4, 0x15, 0x3c, 0x4a, 0x50, 0x0f, 0x5e, 0xfc, 0x93, 0xa0,
	0xde, 0x8e, 0xa0, 0xdd, 0x8e, 0xe0, 0x5d, 0xb5, 0x1d, 0x5e, 0x53, 0x6e, 0x80, 0xbc, 0x00, 0x27,
	0x41, 0xdd, 0x75, 0x38, 0xea, 0xc7, 0x1b, 0x38, 0xdd, 0xa1, 0x9e, 0x83, 0x9d, 0xa0, 0x6e, 0x66,
	0x7f, 0x30, 0x6f, 0x6f, 0x44, 0x40, 0x43, 0x98, 0x47, 0x0a, 0xb7, 0x1a, 0x9b, 0xef, 0x71, 0x89,
	0xa3, 0x39, 0x31, 0xa6, 0xf8, 0x3f, 0x39, 0x6f, 0x67, 0x37, 0xe6, 0xc7, 0xb0, 0x9b, 0x19, 0xcd,
	0x17, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x47, 0x84, 0xa5, 0x03, 0x39, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CmisServiceClient is the client API for CmisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CmisServiceClient interface {
	GetRepository(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Repository, error)
	GetChildren(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisChildren, error)
	GetObject(ctx context.Context, in *CmisID, opts ...grpc.CallOption) (*CmisObject, error)
	CreateObject(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisObject, error)
	DeleteObject(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisObject, error)
}

type cmisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCmisServiceClient(cc grpc.ClientConnInterface) CmisServiceClient {
	return &cmisServiceClient{cc}
}

func (c *cmisServiceClient) GetRepository(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Repository, error) {
	out := new(Repository)
	err := c.cc.Invoke(ctx, "/cmis.CmisService/getRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmisServiceClient) GetChildren(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisChildren, error) {
	out := new(CmisChildren)
	err := c.cc.Invoke(ctx, "/cmis.CmisService/getChildren", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmisServiceClient) GetObject(ctx context.Context, in *CmisID, opts ...grpc.CallOption) (*CmisObject, error) {
	out := new(CmisObject)
	err := c.cc.Invoke(ctx, "/cmis.CmisService/getObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmisServiceClient) CreateObject(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisObject, error) {
	out := new(CmisObject)
	err := c.cc.Invoke(ctx, "/cmis.CmisService/createObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cmisServiceClient) DeleteObject(ctx context.Context, in *CmisObject, opts ...grpc.CallOption) (*CmisObject, error) {
	out := new(CmisObject)
	err := c.cc.Invoke(ctx, "/cmis.CmisService/deleteObject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CmisServiceServer is the server API for CmisService service.
type CmisServiceServer interface {
	GetRepository(context.Context, *empty.Empty) (*Repository, error)
	GetChildren(context.Context, *CmisObject) (*CmisChildren, error)
	GetObject(context.Context, *CmisID) (*CmisObject, error)
	CreateObject(context.Context, *CmisObject) (*CmisObject, error)
	DeleteObject(context.Context, *CmisObject) (*CmisObject, error)
}

// UnimplementedCmisServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCmisServiceServer struct {
}

func (*UnimplementedCmisServiceServer) GetRepository(ctx context.Context, req *empty.Empty) (*Repository, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRepository not implemented")
}
func (*UnimplementedCmisServiceServer) GetChildren(ctx context.Context, req *CmisObject) (*CmisChildren, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetChildren not implemented")
}
func (*UnimplementedCmisServiceServer) GetObject(ctx context.Context, req *CmisID) (*CmisObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (*UnimplementedCmisServiceServer) CreateObject(ctx context.Context, req *CmisObject) (*CmisObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateObject not implemented")
}
func (*UnimplementedCmisServiceServer) DeleteObject(ctx context.Context, req *CmisObject) (*CmisObject, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}

func RegisterCmisServiceServer(s *grpc.Server, srv CmisServiceServer) {
	s.RegisterService(&_CmisService_serviceDesc, srv)
}

func _CmisService_GetRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmisServiceServer).GetRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmis.CmisService/GetRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmisServiceServer).GetRepository(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmisService_GetChildren_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmisObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmisServiceServer).GetChildren(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmis.CmisService/GetChildren",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmisServiceServer).GetChildren(ctx, req.(*CmisObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmisService_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmisID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmisServiceServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmis.CmisService/GetObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmisServiceServer).GetObject(ctx, req.(*CmisID))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmisService_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmisObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmisServiceServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmis.CmisService/CreateObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmisServiceServer).CreateObject(ctx, req.(*CmisObject))
	}
	return interceptor(ctx, in, info, handler)
}

func _CmisService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmisObject)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CmisServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmis.CmisService/DeleteObject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CmisServiceServer).DeleteObject(ctx, req.(*CmisObject))
	}
	return interceptor(ctx, in, info, handler)
}

var _CmisService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmis.CmisService",
	HandlerType: (*CmisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getRepository",
			Handler:    _CmisService_GetRepository_Handler,
		},
		{
			MethodName: "getChildren",
			Handler:    _CmisService_GetChildren_Handler,
		},
		{
			MethodName: "getObject",
			Handler:    _CmisService_GetObject_Handler,
		},
		{
			MethodName: "createObject",
			Handler:    _CmisService_CreateObject_Handler,
		},
		{
			MethodName: "deleteObject",
			Handler:    _CmisService_DeleteObject_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/cmis.proto",
}
